name: e4s
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas
  - bzip2
  - ca-certificates
  - certifi
  - cudatoolkit=11.3
  - dlib
  - freetype
  - giflib
  - idna
  - intel-openmp
  - jpeg
  - lame
  - lcms2
  - lerc
  - libpng
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - numpy
  - numpy-base
  - openh264
  - openssl
  - pillow
  - pip
  - pycparser
  - pyopenssl
  - pysocks
  - python=3.7.*
  - pytorch-mutex
  - requests
  - setuptools
  - six
  - sqlite
  - tk
  - typing_extensions
  - urllib3
  - wheel
  - zlib
  - zstd
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - torch==1.12.1+cu113
    - torchvision==0.13.1+cu113
    - torchaudio==0.12.1
    - contourpy
    - cycler==0.11.0
    - face-alignment==1.3.5
    - fonttools
    - imageio==2.27.0
    - importlib-metadata==6.1.0
    - importlib-resources==5.12.0
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - llvmlite==0.39.1
    - matplotlib
    - networkx
    - numba==0.56.4
    - opencv-python
    - packaging==23.0
    - protobuf==3.20.3
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pywavelets
    - pyyaml
    - scikit-image
    - scipy
    - tensorboardx
    - tifffile
    - tqdm
    - zipp